### PR TITLE
Fix regression in editmeet caused by introducing date-time conflict check with existing meetings

### LINKED ISSUE #150: [PE-D] Edit meeting with same date time without error message displayed in the app but error thrown in Terminal
Below is the input I entered for editing meeting at 1st index of the meeting list to have the same time as the meeting at the 2nd index of the meeting list.

After I clicked enter on my keyboard, the ISCAM app just freeze with the user input in white and no error message is thrown out which a user should expect to see if no meeting times should be edited to be the same with the existing meetings. However, there is an InvocationTargetException error being thrown in the terminal.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: kaixiangtay/ped#4

### PR DESCRIPTION
**Pull request by Tomashiwa**
Fixes regression from #150.

Changes made:

- Excluded pre-edited meeting from the conflict check in editmeet.

### CODE REVIEW

File: src/main/java/seedu/iscam/logic/commands/RescheduleMeetingCommand.java [hunk 1]
```diff
@@ -55,7 +55,7 @@ public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
 
         ObservableList<Meeting> meetings = model.getFilteredMeetingList();
-        if (index.getZeroBased() >= meetings.size()) {
+        if (index.getZeroBased() >= meetings.size() || index.getZeroBased() < 0) {
```
Comment (frisciliasultan) [inline src/main/java/seedu/iscam/logic/commands/RescheduleMeetingCommand.java]: Perhaps checking whether index < 0 is unnecessary because the error would be thrown from parseIndex method in ParseUtil class?

Comment (Tomashiwa) [reply src/main/java/seedu/iscam/logic/commands/RescheduleMeetingCommand.java]: Good observation, I will be removing that check condition then
