### PR TITLE
Fix a bug where a completed meeting can become incomplete via editmeet command

### LINKED ISSUE #112: [PE-D] Editing a just completed meeting without any parameter but an index causes the meeting to become incomplete again
One can execute `editmeet 3` without a problem. Here, the third meeting is completed.

The meeting status simply switched from completed to not completed.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: JQChong/ped#3

### PR DESCRIPTION
**Pull request by Tomashiwa**
Fixes #112 

Changes made

- Meeting's `isDone` is replaced with a `CompletionStatus` class that has 2 values, `complete` and `incomplete`.
- Prefix for status field in `editmeet` is now `s/`
- Feedback message from `editmeet` has been updated

### CODE REVIEW

File: src/main/java/seedu/iscam/storage/meeting/JsonAdaptedMeeting.java [hunk 1]
```diff
@@ -40,15 +41,15 @@ public JsonAdaptedMeeting(@JsonProperty("client") String clientName, @JsonProper
                               @JsonProperty("location") String location,
                               @JsonProperty("description") String description,
                               @JsonProperty("tags") List<JsonAdaptedMeetingTag> tags,
-                              @JsonProperty("isDone") String isDone) {
+                              @JsonProperty("isDone") String status) {
```
Comment (frisciliasultan) [inline src/main/java/seedu/iscam/storage/meeting/JsonAdaptedMeeting.java]: Very minor, but should the JsonProperty be "status" instead of "isDone"?

**Review by frisciliasultan — APPROVED** [review]
Other than the minor naming inconsistency, LGTM!
